### ISSUE TITLE
Compressing

### ISSUE THREAD

**Issue by 3dm1** [seven332/a7zip#1]
Hi, I'd just like to confirm that there isn't support for compressing files in zip format. If there is, could you please share the steps to do it?

**Comment by seven332** [comment]
Compressing is not supported. Because [ZipOutputStream](https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipOutputStream.html) is enough for me.
Please check the example. https://stackoverflow.com/a/1091817/3450520
