### ISSUE TITLE
Does it support extracting password protected files?

### ISSUE THREAD

**Issue by asthagarg2428** [seven332/a7zip#6]
Does it support extracting password protected files?
And compressing files with password?

**Comment by seven332** [comment]
It supports extracting password protected files.
https://github.com/seven332/a7zip/blob/cba0ce958643a6c861fbe25fc50a4b485e8adf86/library/src/androidTest/java/com/hippo/a7zip/InArchiveTest.java#L299
Compressing file is not supported.
